### ISSUE TITLE
Feature Request: Bulk Data Availability via Parquet

### ISSUE THREAD

**Issue by riordan** [openaq/openaq-open-data#8]
While it's frankly quite extraordinary that you publish your complete data at all, working with the bulk data on S3 as CSV is challenging from a user perspective due to the tremendous number of records spread across a large subset of directories. This is both a function of the partitioning strategy as well as CSV file format.

It would be incredible if in addition to publishing CSVs (therefore maintaining backwards compatibility for users), you were also publishing a variant in [parquet](https://docs.aws.amazon.com/glue/latest/dg/aws-glue-programming-etl-format-parquet-home.html) would allow for more direct usage of the bulk data (e.g. querying directly in data warehouses, with tools like DuckDB).

The file format is columnar (so users only transfer data for the columns they're accessing), typed, and has several modern compression schemes. 

Having this available with something like a date/country or date/provider/country partition structure would be incredibly useful from a user standpoint (faster queries directly of the data, minimizing the athena scan time / enabling direct querying by other compute platforms), and possibly to simplify the export process from your standpoint (1. output all records for the day to a single parquet file, 2. drive the highly-sharded csv export process from that parquet file with athena or duckdb).

If useful for background: I found myself looking at this when I realized that the [BigQuery Public Dataset for OpenAQ](https://console.cloud.google.com/marketplace/product/openaq/real-time-air-quality) seemed to have its pipeline broken since 2022. Obviously, somewhere along the line, their data pipeline broke. But using Parquet availability, it wouldn't matter that Google's pipeline goes down, the table can be registered to read from your data on S3 without too much of a performance penalty.

**Comment by russbiggs** [comment]
Thanks for this comment. We have considered parquet as an output format but ultimately landed with the gzipped csvs for readability and portability for the majority of our users. 

Storage and other fees for the Open Data bucket are generously handled by AWS via an agreement we have. That said we have previously agreed limits on how much data we output, so that its predictable for both parties. This makes adding new formats a bit out of our control at least in the short term. I will keep the parquet suggestion in consideration when re-evaluating our strategy for outputting to the bucket.
